cmake_minimum_required(VERSION 3.22.1)
project(veil)
add_library(veilsys SHARED native_syscalls.cpp)
add_library(veilexploit SHARED kgsl_exploit.c)
add_library(veiltls SHARED tls_mimic.c)
find_library(log-lib log)
find_library(ssl-lib ssl)
find_library(crypto-lib crypto)
target_link_libraries(veilsys ${log-lib})
target_link_libraries(veilexploit ${log-lib})
target_link_libraries(veiltls ${log-lib} ${ssl-lib} ${crypto-lib})
